### ISSUE TITLE
Wrong UTF-8 characters conversion 

### ISSUE THREAD

**Issue by nicStuff** [jnbt/java-properties#5]
While writing down a ü, the tool converted it to its unicode hex numeric code, writing "\ufc". Shouldn't there be also the padding zeros, obtaining "\u00fc"?

Without padding zeros, the language wouldn't be able to understand where the code finishes, so I fear that you lost the character in the conversion and won't be able to recover it unless with a lot of hand work.

**Comment by jnbt** [comment]
You might be right here. When using the Java provided `native2ascii` tool it converts using padding zeros.

Reference for myself:

```bash
$ echo "ü" | native2ascii
\u00fc
```

At the moment I'm pretty short in time. I'll happy to accept a PR here, otherwise this issue might be open for the next 3 weeks. (I'm really sorry here, but I won't make it earlier)

**Comment by parag90** [comment]
I am facing similar issue I am not abel to get the property value @properties[:pageTitle] is returning null. Attaching the file here

**Comment by parag90** [comment]
I am not able to upload file here, Seems github doesn't allow. 
Content of files are encoded in utf-8 with BOM

pageTitle=Review submission

**Comment by parag90** [comment]
Please provide your email so that I can mail you the properties file

**Comment by nicStuff** [comment]
Maybe you could attach a zip containing the file.

**Comment by parag90** [comment]
I am getting this error while uploading zip Unfortunately, we don’t support that file type.  Choose Files Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, or PDF.

Also When I tried converting file to txt and upload

**Comment by parag90** [comment]
Hey Nicola,
PFA the property file.

Regards,
Parag

From: Nicola Baisero
Reply-To: jnbt/java-properties
Date: Tuesday, 6 October 2015 17:14
To: jnbt/java-properties
Cc: Parag Jain
Subject: Re: [java-properties] Wrong UTF-8 characters conversion (#5)


Maybe you could attach a zip containing the file.

**Comment by jnbt** [comment]
I'm going back to usual business the next days. So I'll try to give this issue some time this week.

@parag90  Can you upload the properties file somewhere?

**Comment by jnbt** [comment]
@nicStuff I've released version 0.1.0 which should resolve your issue

**Comment by parag90** [comment]
https://drive.google.com/file/d/0B0ACX8Jp_mjdTWI0U0NxUkNQVjA/view?usp=sharing

@jnbt

**Comment by parag90** [comment]
https://drive.google.com/file/d/0B0ACX8Jp_mjdTWI0U0NxUkNQVjA/view?usp=sharing

**Comment by jnbt** [comment]
Hi @parag90,

thanks for providing the file. I've found the problem: Your file contains a [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) at the beginning.

HEX dump:
```
EF BB BF 70 61 67 65 54 69 74 6C 65 3D
< BOM >   p  a  g  e  T  i  t  l  e  =
```

There was a problem with this gem when loading a BOM-based file using `JavaProperties.load("some/path/foo.properties")` as the first BOM bytes weren't skipped. This is fixed in the current master branch. Perhaps you can test the current master branch in your project:

```ruby
# in Gemfile
gem 'java-properties', :git => 'https://github.com/jnbt/java-properties.git', :ref => '0dbff51'
```

If you're not using `JavaProperties.load` but instead load the file yourself and pass the content to `JavaProperties.parse(...)` you must load the file respecting the BOM marker:

```ruby
File.open("foo.bar", "r:bom|utf-8") do |file|
  JavaProperties.parse(file.read)
end
```

**Comment by parag90** [comment]
@jnbt Thanks a lot for fixing this, Appreciate your support !! I have used load function and it worked

**Comment by jnbt** [comment]
@parag90 Thanks for testing.

Version `0.1.1` is released to RubyGems. You may want to update your dependencies
